spring:
  application:
    name: meta-diaria
  datasource:
    url: jdbc:postgresql://localhost:5432/metadiaria
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: America/Sao_Paulo

server:
  port: 8080

jwt:
  secret: my-super-secret-key-change-in-prod
  expiration: 3600000 # 1h em ms
